function y = protocol_msg(CMD,ID,VAL)

aux1 = dec2hex(CMD);
aux2 = dec2hex(ID);
aux3 = dec2hex(VAL);
LSB = dec2hex(bitand(VAL, 255));     
MSB = dec2hex(bitshift(VAL, -8));


% SOF | ID | VAL[0]| VAL[1] | CHK | EOK
y = "0xAA" + ...
    '0x' + aux1 + ...
    '0x' + aux2 + ...
    '0x' + MSB + ...
    '0x' + LSB + ...
    '0x' + sumHex(aux1,aux2,VAL) + ...
    '0xBB';
% y = "AA" + ...
%      aux1 + ...
%      aux2 + ...
%      MSB + ...
%      LSB + ...
%      sumHex(aux1,aux2,VAL) + ...
%     'BB';

end

